version: '3'

services:
  flask_app:
    build:
      context: .
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ec_cert.pem:/etc/nginx/ec_cert.pem
      - ./nginx/ec_key.pem:/etc/nginx/ec_key.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app
